version: "2.1"
services:
  openssh-server:
    image: ghcr.io/linuxserver/openssh-server
    container_name: openssh-server
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=ubuntu
    volumes:
      - ./config/destination:/config
    ports:
      - 2222:2222
  openssh-server-single-try:
    image: ghcr.io/linuxserver/openssh-server
    container_name: openssh-server-single-try
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=ubuntu
    volumes:
      - ./config/destination-single-try:/config
    ports:
      - 2223:2222
  bastion:
    image: ghcr.io/linuxserver/openssh-server
    container_name: bastion
    hostname: bastion
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=ubuntu
    volumes:
      - ./config/bastion:/config
    ports:
      - 2224:2222
